[package]
name = "pathtracer"
version = "0.1.0"
authors = ["AregevDev <aregevdev@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
image = "0.23.0-preview.0"

[profile.release]
debug = true